language: scala
scala:
- 2.11.2
jdk:
- oraclejdk7
- openjdk7
notifications:
  email:
  - nick.edwards.uk@gmail.com
env:
  global:
  - secure: kasSr4GnvSrBc4QfpZKPQ0WQ5cZnQKKb/KsG7DBgbcil4BbRXZ36hsMUvat+RXqkuKLhBi7Y3mrn26+mBnp21+Inwe4PQp5PxN/s5zyvDLekpXx5cspEsS2S4KNz+Z7o9h2FXNhGtRnX2ILfeQYxUb+zq+4aoxpVRdn/cclIQiA=
  - secure: CXgtyhHfuk6tZRjFLbLo3Iu39vVt5NwtrmxO3VLW9M32fAvki3YIlpZ7qfXKYUn/QoMrNNP+ZKN/BnbsLZqvgMVerIOR77uUdNhG44w99U1C9G6/7qTiNfF0iAIwwwgtOkJzTlkQbs7vAjHgRY9bRnRQvjwYuZCSoIsI9uC6XUg=
  - secure: FfoD/vSuDe6ymTvvoVCVHSsl4hx9IpI19xYMm49KLqxLPNjCcDG7R2RlvMfz+U007C0IWmJXL0AMMCu+Pb+mOrDSbYszbawCL5pYtmFk6ML2/enw/0DAJ7/9uRew+ZaZq04RtC0icxP5qLgUUFje2E9fnTCcM+eyjBjat24qTqU=
  - secure: PdTKUUxl8gaDM02djLE0329rO37LvLeQghJOrLwhHmNrBnqvHYYh5iaWrJ+zCoPvAS4xGU0pyQQep/2ngfsMzMQbjHKYnj6fz3r94VSjo71vgAyTxD2vsgag7pyz3VzadKC4hvPxZJfxeWWabm+oU6RY7nMhRJVW3HrRPMqiWe8=
after_success:
- test "${TRAVIS_PULL_REQUEST}" = 'false' && test "${TRAVIS_JDK_VERSION}" = 'oraclejdk7'
  && sh "$TRAVIS_BUILD_DIR/script/travis-ci-bintray-credentials.sh" && sbt 'set version
  := version.value + "." + System.getenv("TRAVIS_BUILD_NUMBER")' publish
